mixins:
  - helm3:
      repositories:
        bitnami:
          url: "https://charts.bitnami.com/bitnami"

name: mysql
version: "0.1.0"
registry: jeremyrickard

credentials:
  - name: kubeconfig
    path: /root/.kube/config

install:
  - helm3:
      description: "Install MySQL"
      name: porter-ci-mysql
      chart: bitnami/mysql
      version: "6.14.2"
uninstall:
  - helm3:
      description: "Uninstall MySQL"
      releases:
        - porter-ci-mysql
      purge: true
